name: "dbt_assignment"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"

models:
  dbt_assignment:
    stg:
      +materialized: table
      +schema: stg
    dwh:
      +materialized: table
      +schema: dwh
    dm:
      +materialized: table
      +schema: dm

seeds:
  schema: raw
